# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1966266397af23d944cc2cd4e0e81fa6e4a15b4db1fcf059c564abcaa2eaf661d13668074af1754bf5ae6a13e1efd706b1d4f0730c64ab5abdce921df351377f

test:
  secret_key_base: 0b62c9573af5a01d64c927075ea93d3db1dbb52dc2474fa24eb068583f3811e58923b50b2f85b572e78c6c5ddd6c5b0f75e0ab652c5a6827726098a39e46591f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
